# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.provider "virtualbox" do |vbox,	override|
	  override.vm.box = "saucy"
	  override.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"
	  vbox.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provider "kvm" do |kvm, override|
	  override.vm.box = "saucy"
	  override.vm.network :private_network, ip: "192.168.192.122"
  end

  config.vm.provider "lxc" do |lxc, override|
	  override.vm.box = "lxc-saucy"
	  override.vm.box_url = "http://bit.ly/vagrant-lxc-saucy64-2013-10-23"
  end

  config.vm.provision :puppet do |puppet|
	puppet.manifests_path = "../puppet/vsfs/manifests/"
	puppet.module_path = "../puppet/vsfs/modules/"
	puppet.manifest_file  = "devbox.pp"
  end
end
