# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb, override|
	  # Use VBoxManage to customize the VM. For example to change memory:
	  vb.customize ["modifyvm", :id, "--memory", "2048"]
	  override.vm.box = "ubuntu"
	  override.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"
	  override.vbguest.auto_update = true
  end

  config.vm.provider :digital_ocean do |provider, override|
	  override.ssh.private_key_path = '~/.ssh/id_rsa'
	  override.vm.box = 'digital_ocean'
	  override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
	  provider.image = 'Ubuntu 13.10 x64'
  end

  # Install puppet before provision
  config.vm.provision "shell", path: "https://raw.github.com/vsfs/vsfs-devtools/master/install-devbox.sh"
end
