# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.provider "virtualbox" do |vbox,	override|
	  override.vm.box = "raring"
	  override.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
	  vbox.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.provider "kvm" do |kvm, override|
	  override.vm.box = "raring"
	  override.vm.network :private_network, ip: "192.168.192.122"
  end

  config.vm.provider "lxc" do |lxc, override|
	  override.vm.box = "lxc-raring"
	  override.vm.box_url = "http://dl.dropbox.com/u/13510779/lxc-raring-amd64-2013-04-21.box"
  end

  config.vm.provision :puppet do |puppet|
	puppet.manifests_path = "../puppet/"
	puppet.module_path = "../puppet/"
	puppet.manifest_file  = "default.pp"
  end
end
