# -*- mode: ruby -*-
# vi: set ft=ruby :

$inline_script = <<SCRIPT
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python
sudo easy_install pip
sudo yum install python-devel
sudo pip install buildbot buildbot-slave
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define :master do |master_config|
	master_config.vm.box = "ubuntu"
	master_config.vm.box_url = "http://cloud-images.ubuntu.com/quantal/current/quantal-server-cloudimg-vagrant-amd64-disk1.box"
  end

  config.vm.define :slave do |slave|
    slave.vm.box = 'raring'
  end

  config.vm.define :centos do |centos_config|
	centos_config.vm.box = "centos"
  end

  config.vm.provider :virtualbox do |vb|
	# Don't boot with headless mode
	vb.gui = false

	# Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision :puppet do |puppet|
	  puppet.manifests_path = "../puppet/vsfs/manifests"
	  puppet.module_path = "../puppet/vsfs/modules"
	  puppet.manifest_file  = "devbox.pp"
  end

  config.vm.provision :shell do |s|
	s.inline = $inline_script
  end
end
