# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.define :master do |master_config|
	master_config.vm.box = "ubuntu"
    master_config.vm.box_url = "http://cloud-images.ubuntu.com/quantal/current/quantal-server-cloudimg-vagrant-amd64-disk1.box"
  end

  config.vm.define :centos do |centos_config|
	centos_config.vm.box = "centos"
	centos_config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130309.box"
  end

  config.vm.provider :virtualbox do |vb|
	# Don't boot with headless mode
     vb.gui = false

     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  config.vm.provision :puppet do |puppet|
	  puppet.manifests_path = "../puppet/puppet-vsfs/manifests"
	  puppet.module_path = "../puppet/puppet-vsfs/modules"
	  puppet.manifest_file  = "init.pp"
  end
end
